#!/usr/bin/env bash
# script that transfers a file from our client to a server

path=$1
server_ip=$2
server_username=$3
path_to_ssh_private_key=$4

if [ $# -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

scp -i $path_to_private_key -o StrictHostKeyChecking=no $path $server_username@$server_ip:~/

