#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.
# - Sends traffic to web-01 and web-02.

# Update and upgrade package lists
sudo apt-get -y update
sudo apt-get -y upgrade

# Install HAProxy
sudo apt-get -y install haproxy

# Enable HAProxy to be managed via init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Backup the original HAProxy configuration
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.original

# Create a new HAProxy configuration file
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  10000
    timeout server  10000

frontend http_front
    bind *:80
    stats uri /haproxy?stats
    default_backend http_back

backend http_back
    balance roundrobin
    option httpclose
    option forwardfor
    server web-01 18.209.152.222:80 check
    server web-02 52.86.165.89:80 check
EOL

# Restart HAProxy to apply the new configuration
sudo service haproxy restart
