#!/usr/bin/env bash
cat ~/.ssh/school.pub | ssh ubuntu@52.3.254.6 "mkdir -p ~/.ssh && chmod 700 ~/.ssh && touch ~/.ssh/authorized_keys && chmod 600 ~/.ssh/authorized_keys && cat >> ~/.ssh/authorized_keys"
ssh -i ~/.ssh/school ubuntu@52.3.254.6
